name: Release Workflow

on:
  # Triggers the workflow after the Test Workflow has completed
  # workflow_run:
  #   workflows: ['Test Workflow']
  #   types:
  #     - completed
  #   branches:
  #     - development
  #     - 'release/*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run && github.event.workflow_run.conclusion == 'success' || true }}
    environment: 'Release NPM'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GIT_USER: ${{ secrets.GIT_USER }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      RELEASE_BRANCH: ${{ github.event.workflow_run.head_branch || github.ref }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_TOKEN }}
          ref: ${{ env.RELEASE_BRANCH }}
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-node-
      - name: Auth NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" > ~/.npmrc
      - name: Auth Git
        run: |
          git config user.email "${{ env.GIT_EMAIL }}"
          git config user.name "${{ env.GIT_USER }}"
      - name: Install Deps
        run: npm ci --ignore-scripts

      - name: Build packages
        run: npx nx run-many --target=build --all

      - name: Release Next
        if: ${{ env.RELEASE_BRANCH == 'development' }}
        run: RELEASE_TAG=next npm run release-tag

      - name: Release Latest
        if: ${{ startsWith(env.RELEASE_BRANCH, 'release/') }}
        run: npm run release-branch

      - name: Release Error Log
        if: failure()
        run: cat libs/lerna-debug.log
